name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      BuildConfiguration: Release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/setup/usage-examples.md
    - name: Setup GitTools
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'
        
    # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:configuration=$BuildConfiguration /p:AssemblyInformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} /p:Version=${{ steps.gitversion.outputs.fullSemVer }} /p:AssemblyVersion=$GITVERSION_ASSEMBLYSEMFILEVER
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:configuration=$BuildConfiguration
    - name: Pack
      run: dotnet pack Capsaicin.CodeAnalysis.Common/Capsaicin.CodeAnalysis.Common.csproj --no-build --verbosity normal
