name: .NET

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main

jobs:
  build:
    if: ${{ !github.event.issue.pull_request }}

    runs-on: windows-latest
    env:
      BuildConfiguration: Debug

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/setup/usage-examples.md
    - name: Setup GitTools
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'
        
    # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.9

    - name: Set build configuration
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "set build configuration to Release"
      env:
        BuildConfiguration: Release
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:configuration=${{ env.BuildConfiguration }} /p:AssemblyInformationalVersion=${{ env.GitVersion_InformationalVersion }} /p:Version=${{ env.GitVersion_FullSemVer }} /p:AssemblyVersion=${{ env.GitVersion_AssemblySemFileVer }}
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal /p:configuration=${{ env.BuildConfiguration }}
    - name: Pack
      run: dotnet pack Capsaicin.CodeAnalysis.Common/Capsaicin.CodeAnalysis.Common.csproj --no-build --no-restore --verbosity normal /p:configuration=${{ env.BuildConfiguration }} /p:AssemblyInformationalVersion=${{ env.GitVersion_InformationalVersion }} /p:Version=${{ env.GitVersion_FullSemVer }} /p:AssemblyVersion=${{ env.GitVersion_AssemblySemFileVer }}
    - name: Push nuget package
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
